# Generated by Django 3.2.5 on 2021-11-15 06:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGsEmissions',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data_id', models.AutoField(help_text='unique value for data', primary_key=True, serialize=False, verbose_name='GHGs Emissions ID')),
                ('year', models.IntegerField(help_text='Year', verbose_name='Year')),
                ('value', models.FloatField(help_text='value of GHG emissions', verbose_name='Emissions value')),
                ('country_id', models.ForeignKey(help_text='Foreign key relation to Countries model', on_delete=django.db.models.deletion.CASCADE, to='countries.countries', verbose_name='Counrties')),
                ('emission_category_id', models.ForeignKey(help_text='Foreign key relation to Categories model', on_delete=django.db.models.deletion.CASCADE, to='categories.emissioncategories', verbose_name='Emission category')),
            ],
            options={
                'verbose_name': 'GHGs Emission Data',
                'db_table': 'ghg_emission_data',
                'ordering': ('year',),
            },
        ),
    ]
